# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.cache/wt [current_project]
set_property parent.project_path D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
set_property ip_output_repo d:/Workspace/ECE_475_FINAL/ECE_475_FINAL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/sources_1/new/alu_control_signals.vh
  D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/sources_1/new/opcodes.vh
}
read_mem D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/sources_1/new/mem_8k.mem
read_verilog -library xil_defaultlib {
  D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/sources_1/new/alu_32_behavioral.v
  D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/sources_1/new/bsp_io.v
  D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/sources_1/new/cpu.v
  D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/sources_1/new/cu_combinational.v
  D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/sources_1/new/sys_ram_8k.v
  D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/sources_1/new/system_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/constrs_1/new/nexys4_bsp.xdc
set_property used_in_implementation false [get_files D:/Workspace/ECE_475_FINAL/ECE_475_FINAL.srcs/constrs_1/new/nexys4_bsp.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
